### PR TITLE
[WIP] Implement MPI_Comm_{get,set}_name

### PR DESCRIPTION
**Pull request by marmistrz**
* [x] implement functions
* [x] create tests

### CODE REVIEW

**Comment by bsteinb** [comment]
Well, have fun with your t-shirt, I guess.

**Comment by marmistrz** [comment]
Hi, I actually want to get this finished but I simply didn't have the time. A pretty busy time at the university this semester. I'll comment here when I have the tests implemented.

**Comment by bsteinb** [comment]
All right. It has been a while since I was a student at university and I guess I have already forgotten how hectic it gets. Sorry about that.

**Comment by marmistrz** [comment]
This should be ready. I'm not doing any extra error handling, since an MPI program will crash anyway when an error is encountered. 

Let me know if this should be changed.

**Comment by bsteinb** [comment]
The error handling is fine for now. I will probably want to change it once things start moving in the direction of #32, but that could take a while.

Could I ask you to change the headings for the MPI standard reference in the documentation comments to be adapted to the way they are done in the rest of the project (`# Standard section(s)` instead of `# MPI standard reference`)?

**Comment by marmistrz** [comment]
The issue with `Standard section(s)` is that `standard` in this context looks like an adjective (a section, which is standard) than a noun (a section from the standard). 

`MPI standard reference` or `MPI standard section` would be much more clear to people who don't have thorough experience with MPI (most people I know who use MPI have never touched the standard and have learned from various tutorials)

**Comment by bsteinb** [comment]
All right, we have discussed this issue before. My point of view has not changed and it seems neither has yours. I do not think though that either side gains anything by formatting these references in a different way on two methods out of the whole API.

**Comment by bsteinb** [comment]
Thanks for the contribution.

**Comment by marmistrz** [comment]
A middle ground could be to explain this in the README. What do you think?

**Comment by bsteinb** [comment]
Sure, I can get behind that. Then I would also add it to the crate level documentation though.

**Pull request merged**
